### ISSUE TITLE
Getting profile info bug?

### ISSUE THREAD

**Issue by SmithPeder** [webkom/lego-webapp#1071]
I don't know if this is just me, but it's a cross device problem for me so i can imagine that others have the same issue. When opening the front page the profile image and the name will not load until i go to the profile.

![screenshot from 2018-01-28 01-27-19](https://user-images.githubusercontent.com/23152018/35477732-a282532a-03ca-11e8-8e18-174c1bc988f2.png)

**Comment by cherrybeans** [comment]
Same issue here.

**Comment by ekmartin** [comment]
Do you have any errors in the Chrome console when it happens?

**Comment by odinuge** [comment]
After some investigation, this turned out to be a pod without working dns/network. That also resulted in no exceptions reported to sentry. #1081 Adds a healthcheck to shut down instances without access to the api, that shold fix issues like this. 😀

I will also add a better, and more deterministic handling of stuff like this in the ssr.
